-- Création de la base de données des statues

-- Table Ville
CREATE TABLE Ville (
    CODVIL INTEGER PRIMARY KEY,
    ANOM VARCHAR(100),
    NNOM VARCHAR(100)
);

-- Table Musée
CREATE TABLE Musee (
    CODVIL INTEGER,
    CODMUS INTEGER CHECK (CODMUS BETWEEN 1 AND 100),
    NOMMUS VARCHAR(200),
    CONSER VARCHAR(100),
    PRIMARY KEY (CODVIL, CODMUS),
    FOREIGN KEY (CODVIL) REFERENCES Ville(CODVIL)
);

-- Table Site
CREATE TABLE Site (
    CODVIL INTEGER,
    CODSIT INTEGER CHECK (CODSIT BETWEEN 1 AND 100),
    DESSIT VARCHAR(200),
    PRIMARY KEY (CODVIL, CODSIT),
    FOREIGN KEY (CODVIL) REFERENCES Ville(CODVIL)
);

-- Table Bâtiment
CREATE TABLE Batiment (
    CODVIL INTEGER,
    CODSIT INTEGER CHECK (CODSIT BETWEEN 1 AND 100),
    CODBAT INTEGER CHECK (CODBAT BETWEEN 1 AND 50),
    DESBAT VARCHAR(200),
    TYPBAT VARCHAR(50),
    DATBAT VARCHAR(50),
    PRIMARY KEY (CODVIL, CODSIT, CODBAT),
    FOREIGN KEY (CODVIL, CODSIT) REFERENCES Site(CODVIL, CODSIT)
);

-- Table Éditeur
CREATE TABLE Editeur (
    NUMEDI INTEGER CHECK (NUMEDI BETWEEN 1 AND 1000) PRIMARY KEY,
    NOMEDI VARCHAR(200)
);

-- Table Ouvrage
CREATE TABLE Ouvrage (
    NUMOUV INTEGER CHECK (NUMOUV BETWEEN 1 AND 1000000) PRIMARY KEY,
    TITOUV VARCHAR(500),
    DATEDI DATE,
    NUMEDI INTEGER,
    FOREIGN KEY (NUMEDI) REFERENCES Editeur(NUMEDI)
);

-- Table Auteur
CREATE TABLE Auteur (
    AUT INTEGER PRIMARY KEY,
    NOMAUT VARCHAR(100),
    NATION VARCHAR(50),
    TITAUT VARCHAR(100)
);

-- Table Statue
CREATE TABLE Statue (
    NUMSTA INTEGER CHECK (NUMSTA BETWEEN 1 AND 9999999) PRIMARY KEY,
    TYPSTA VARCHAR(50),
    DATSTA VARCHAR(50),
    DESSTA VARCHAR(500),
    SCUSTA VARCHAR(100),
    CODVIL_O INTEGER,  -- Ville d'origine
    CODVIL_M INTEGER,  -- Ville du musée
    CODMUS INTEGER,        -- Code du musée
    CODVIL_S INTEGER,  -- Ville du site
    CODSIT INTEGER,        -- Code du site
    CODBAT INTEGER,        -- Code du bâtiment
    FOREIGN KEY (CODVIL_O) REFERENCES Ville(CODVIL),
    FOREIGN KEY (CODVIL_M, CODMUS) REFERENCES Musee(CODVIL, CODMUS),
    FOREIGN KEY (CODVIL_S, CODSIT, CODBAT) REFERENCES Batiment(CODVIL, CODSIT, CODBAT)
);

-- Table Info_statue (relation entre Statue et Ouvrage)
CREATE TABLE Info_statue (
    NUMSTA INTEGER,
    NUMOUV INTEGER,
    NUMPAG INTEGER CHECK (NUMPAG BETWEEN 1 AND 10000),
    PRIMARY KEY (NUMSTA, NUMOUV),
    FOREIGN KEY (NUMSTA) REFERENCES Statue(NUMSTA),
    FOREIGN KEY (NUMOUV) REFERENCES Ouvrage(NUMOUV)
);

-- Table Co_auteur (relation entre Ouvrage et Auteur)
CREATE TABLE Co_auteur (
    NUMOUV INTEGER,
    AUT INTEGER,
    PRIMARY KEY (NUMOUV, AUT),
    FOREIGN KEY (NUMOUV) REFERENCES Ouvrage(NUMOUV),
    FOREIGN KEY (AUT) REFERENCES Auteur(AUT)
);
