#!/usr/bin/env sh

. gsh_gettext.sh

GSH_VERSION='v0.6.0-18-g0063b3c'

echo "Gameshell $GSH_VERSION"

echo

echo $(gettext "The latest version of Gameshell is available at")
echo "    https://github.com/phyver/GameShell"
